
p3_execute: main_p3.cc
	g++ -Wall -g -std=c++17 -Wno-class-conversion -Wno-sign-compare -o p3_exe main_p3.cc
	
clean:
	rm -f *.o p3_exe

run:
	./p3_exe 

execute:
	rm -f *.o p3_exe
	g++ -Wall -g -std=c++17 -Wno-class-conversion -Wno-sign-compare -o p3_exe main_p3.cc
